//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CslaModelTemplates.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DalText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DalText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CslaModelTemplates.Resources.DalText", typeof(DalText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group has been changed in the meantime..
        /// </summary>
        public static string Group_Concurrency {
            get {
                return ResourceManager.GetString("Group_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the group has failed..
        /// </summary>
        public static string Group_DeleteFailed {
            get {
                return ResourceManager.GetString("Group_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group with code {0} already exists..
        /// </summary>
        public static string Group_GroupCodeExists {
            get {
                return ResourceManager.GetString("Group_GroupCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new group has failed..
        /// </summary>
        public static string Group_InsertFailed {
            get {
                return ResourceManager.GetString("Group_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested group has not been found..
        /// </summary>
        public static string Group_NotFound {
            get {
                return ResourceManager.GetString("Group_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the group has failed..
        /// </summary>
        public static string Group_UpdateFailed {
            get {
                return ResourceManager.GetString("Group_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the member with name {0} has failed..
        /// </summary>
        public static string Member_DeleteFailed {
            get {
                return ResourceManager.GetString("Member_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member with name {0} already exists..
        /// </summary>
        public static string Member_Exists {
            get {
                return ResourceManager.GetString("Member_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new member with name {0} has failed..
        /// </summary>
        public static string Member_InsertFailed {
            get {
                return ResourceManager.GetString("Member_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested member with name {0} has not been found..
        /// </summary>
        public static string Member_NotFound {
            get {
                return ResourceManager.GetString("Member_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new members has failed..
        /// </summary>
        public static string Membership_InsertFailed {
            get {
                return ResourceManager.GetString("Membership_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the player with code {0} has failed..
        /// </summary>
        public static string Player_DeleteFailed {
            get {
                return ResourceManager.GetString("Player_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new player with code {0} has failed..
        /// </summary>
        public static string Player_InsertFailed {
            get {
                return ResourceManager.GetString("Player_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested player has not been found..
        /// </summary>
        public static string Player_NotFound {
            get {
                return ResourceManager.GetString("Player_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player with code {0} already exists..
        /// </summary>
        public static string Player_PlayerCodeExists {
            get {
                return ResourceManager.GetString("Player_PlayerCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the player with code {0} has failed..
        /// </summary>
        public static string Player_UpdateFailed {
            get {
                return ResourceManager.GetString("Player_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested team has not been found..
        /// </summary>
        public static string RenameTeam_NotFound {
            get {
                return ResourceManager.GetString("RenameTeam_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming the team has failed..
        /// </summary>
        public static string RenameTeam_RenameFailed {
            get {
                return ResourceManager.GetString("RenameTeam_RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team has been changed in the meantime..
        /// </summary>
        public static string SimpleTeam_Concurrency {
            get {
                return ResourceManager.GetString("SimpleTeam_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the team because others belong to it..
        /// </summary>
        public static string SimpleTeam_Delete_Others {
            get {
                return ResourceManager.GetString("SimpleTeam_Delete_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the team has failed..
        /// </summary>
        public static string SimpleTeam_DeleteFailed {
            get {
                return ResourceManager.GetString("SimpleTeam_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new team has failed..
        /// </summary>
        public static string SimpleTeam_InsertFailed {
            get {
                return ResourceManager.GetString("SimpleTeam_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested team has not been found..
        /// </summary>
        public static string SimpleTeam_NotFound {
            get {
                return ResourceManager.GetString("SimpleTeam_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with code {0} already exists..
        /// </summary>
        public static string SimpleTeam_TeamCodeExists {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the team has failed..
        /// </summary>
        public static string SimpleTeam_UpdateFailed {
            get {
                return ResourceManager.GetString("SimpleTeam_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team with code {0} has been changed in the meantime..
        /// </summary>
        public static string SimpleTeamSetItem_Concurrency {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the team with code {0} has failed..
        /// </summary>
        public static string SimpleTeamSetItem_DeleteFailed {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new team with code {0} has failed..
        /// </summary>
        public static string SimpleTeamSetItem_InsertFailed {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team with code {0} has not been found..
        /// </summary>
        public static string SimpleTeamSetItem_NotFound {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with code {0} already exists..
        /// </summary>
        public static string SimpleTeamSetItem_TeamCodeExists {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the team with code {0} has failed..
        /// </summary>
        public static string SimpleTeamSetItem_UpdateFailed {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team has been changed in the meantime..
        /// </summary>
        public static string Team_Concurrency {
            get {
                return ResourceManager.GetString("Team_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the team because others belong to it..
        /// </summary>
        public static string Team_Delete_Others {
            get {
                return ResourceManager.GetString("Team_Delete_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the team has failed..
        /// </summary>
        public static string Team_DeleteFailed {
            get {
                return ResourceManager.GetString("Team_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new team has failed..
        /// </summary>
        public static string Team_InsertFailed {
            get {
                return ResourceManager.GetString("Team_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested team has not been found..
        /// </summary>
        public static string Team_NotFound {
            get {
                return ResourceManager.GetString("Team_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with code {0} already exists..
        /// </summary>
        public static string Team_TeamCodeExists {
            get {
                return ResourceManager.GetString("Team_TeamCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the team has failed..
        /// </summary>
        public static string Team_UpdateFailed {
            get {
                return ResourceManager.GetString("Team_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team with code {0} has been changed in the meantime..
        /// </summary>
        public static string TeamSetItem_Concurrency {
            get {
                return ResourceManager.GetString("TeamSetItem_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the team with code {0} has failed..
        /// </summary>
        public static string TeamSetItem_DeleteFailed {
            get {
                return ResourceManager.GetString("TeamSetItem_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new team with code {0} has failed..
        /// </summary>
        public static string TeamSetItem_InsertFailed {
            get {
                return ResourceManager.GetString("TeamSetItem_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team with code {0} has not been found..
        /// </summary>
        public static string TeamSetItem_NotFound {
            get {
                return ResourceManager.GetString("TeamSetItem_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with code {0} already exists..
        /// </summary>
        public static string TeamSetItem_TeamCodeExists {
            get {
                return ResourceManager.GetString("TeamSetItem_TeamCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the team with code {0} has failed..
        /// </summary>
        public static string TeamSetItem_UpdateFailed {
            get {
                return ResourceManager.GetString("TeamSetItem_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the player with code [ {0} ] {1} has failed..
        /// </summary>
        public static string TeamSetPlayer_DeleteFailed {
            get {
                return ResourceManager.GetString("TeamSetPlayer_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new player with code [ {0} ] {1} has failed..
        /// </summary>
        public static string TeamSetPlayer_InsertFailed {
            get {
                return ResourceManager.GetString("TeamSetPlayer_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested player with code [ {0} ] {1} has not been found..
        /// </summary>
        public static string TeamSetPlayer_NotFound {
            get {
                return ResourceManager.GetString("TeamSetPlayer_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player with code [ {0} ] {1} already exists..
        /// </summary>
        public static string TeamSetPlayer_PlayerCodeExists {
            get {
                return ResourceManager.GetString("TeamSetPlayer_PlayerCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the player with code [ {0} ] {1} has failed..
        /// </summary>
        public static string TeamSetPlayer_UpdateFailed {
            get {
                return ResourceManager.GetString("TeamSetPlayer_UpdateFailed", resourceCulture);
            }
        }
    }
}
