//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CslaModelTemplates.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DalText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DalText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CslaModelTemplates.Resources.DalText", typeof(DalText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested root has not been found..
        /// </summary>
        public static string RenameRoot_NotFound {
            get {
                return ResourceManager.GetString("RenameRoot_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming the root has failed..
        /// </summary>
        public static string RenameRoot_RenameFailed {
            get {
                return ResourceManager.GetString("RenameRoot_RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root has been changed in the meantime..
        /// </summary>
        public static string Root_Concurrency {
            get {
                return ResourceManager.GetString("Root_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the root because others belong to it..
        /// </summary>
        public static string Root_Delete_Others {
            get {
                return ResourceManager.GetString("Root_Delete_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the root has failed..
        /// </summary>
        public static string Root_DeleteFailed {
            get {
                return ResourceManager.GetString("Root_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new root has failed..
        /// </summary>
        public static string Root_InsertFailed {
            get {
                return ResourceManager.GetString("Root_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested root has not been found..
        /// </summary>
        public static string Root_NotFound {
            get {
                return ResourceManager.GetString("Root_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root with code {0} already exists..
        /// </summary>
        public static string Root_RootCodeExists {
            get {
                return ResourceManager.GetString("Root_RootCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the root has failed..
        /// </summary>
        public static string Root_UpdateFailed {
            get {
                return ResourceManager.GetString("Root_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the root item with code {0} has failed..
        /// </summary>
        public static string RootItem_DeleteFailed {
            get {
                return ResourceManager.GetString("RootItem_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new root item with code {0} has failed..
        /// </summary>
        public static string RootItem_InsertFailed {
            get {
                return ResourceManager.GetString("RootItem_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested root item has not been found..
        /// </summary>
        public static string RootItem_NotFound {
            get {
                return ResourceManager.GetString("RootItem_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root item with code {0} already exists..
        /// </summary>
        public static string RootItem_RootItemCodeExists {
            get {
                return ResourceManager.GetString("RootItem_RootItemCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the root item with code {0} has failed..
        /// </summary>
        public static string RootItem_UpdateFailed {
            get {
                return ResourceManager.GetString("RootItem_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root has been changed in the meantime..
        /// </summary>
        public static string SimpleRoot_Concurrency {
            get {
                return ResourceManager.GetString("SimpleRoot_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the root because others belong to it..
        /// </summary>
        public static string SimpleRoot_Delete_Others {
            get {
                return ResourceManager.GetString("SimpleRoot_Delete_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the root has failed..
        /// </summary>
        public static string SimpleRoot_DeleteFailed {
            get {
                return ResourceManager.GetString("SimpleRoot_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new root has failed..
        /// </summary>
        public static string SimpleRoot_InsertFailed {
            get {
                return ResourceManager.GetString("SimpleRoot_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested root has not been found..
        /// </summary>
        public static string SimpleRoot_NotFound {
            get {
                return ResourceManager.GetString("SimpleRoot_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root with code {0} already exists..
        /// </summary>
        public static string SimpleRoot_RootCodeExists {
            get {
                return ResourceManager.GetString("SimpleRoot_RootCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the root has failed..
        /// </summary>
        public static string SimpleRoot_UpdateFailed {
            get {
                return ResourceManager.GetString("SimpleRoot_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root with code {0} has been changed in the meantime..
        /// </summary>
        public static string SimpleRootSetItem_Concurrency {
            get {
                return ResourceManager.GetString("SimpleRootSetItem_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the root with code {0} has failed..
        /// </summary>
        public static string SimpleRootSetItem_DeleteFailed {
            get {
                return ResourceManager.GetString("SimpleRootSetItem_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new root with code {0} has failed..
        /// </summary>
        public static string SimpleRootSetItem_InsertFailed {
            get {
                return ResourceManager.GetString("SimpleRootSetItem_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root with code {0} has not been found..
        /// </summary>
        public static string SimpleRootSetItem_NotFound {
            get {
                return ResourceManager.GetString("SimpleRootSetItem_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root with code {0} already exists..
        /// </summary>
        public static string SimpleRootSetItem_RootCodeExists {
            get {
                return ResourceManager.GetString("SimpleRootSetItem_RootCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the root with code {0} has failed..
        /// </summary>
        public static string SimpleRootSetItem_UpdateFailed {
            get {
                return ResourceManager.GetString("SimpleRootSetItem_UpdateFailed", resourceCulture);
            }
        }
    }
}
