//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CslaModelTemplates.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CslaModelTemplates.Resources.ValidationText", typeof(ValidationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new root name is required..
        /// </summary>
        public static string RenameRoot_RootName_Required {
            get {
                return ResourceManager.GetString("RenameRoot_RootName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root code cannot exceed {1} characters..
        /// </summary>
        public static string Root_RootCode_MaxLength {
            get {
                return ResourceManager.GetString("Root_RootCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root code is required..
        /// </summary>
        public static string Root_RootCode_Required {
            get {
                return ResourceManager.GetString("Root_RootCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root name cannot exceed {1} characters..
        /// </summary>
        public static string Root_RootName_MaxLength {
            get {
                return ResourceManager.GetString("Root_RootName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root name is required..
        /// </summary>
        public static string Root_RootName_Required {
            get {
                return ResourceManager.GetString("Root_RootName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root item code cannot exceed {1} characters..
        /// </summary>
        public static string RootItem_RootItemCode_MaxLength {
            get {
                return ResourceManager.GetString("RootItem_RootItemCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root item code is not unique..
        /// </summary>
        public static string RootItem_RootItemCode_NotUnique {
            get {
                return ResourceManager.GetString("RootItem_RootItemCode_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root item code is required..
        /// </summary>
        public static string RootItem_RootItemCode_Required {
            get {
                return ResourceManager.GetString("RootItem_RootItemCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root item name cannot exceed {1} characters..
        /// </summary>
        public static string RootItem_RootItemName_MaxLength {
            get {
                return ResourceManager.GetString("RootItem_RootItemName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root item name is required..
        /// </summary>
        public static string RootItem_RootItemName_Required {
            get {
                return ResourceManager.GetString("RootItem_RootItemName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root code cannot exceed {1} characters..
        /// </summary>
        public static string SimpleRoot_RootCode_MaxLength {
            get {
                return ResourceManager.GetString("SimpleRoot_RootCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root code is required..
        /// </summary>
        public static string SimpleRoot_RootCode_Required {
            get {
                return ResourceManager.GetString("SimpleRoot_RootCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root name cannot exceed {1} characters..
        /// </summary>
        public static string SimpleRoot_RootName_MaxLength {
            get {
                return ResourceManager.GetString("SimpleRoot_RootName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root name is required..
        /// </summary>
        public static string SimpleRoot_RootName_Required {
            get {
                return ResourceManager.GetString("SimpleRoot_RootName_Required", resourceCulture);
            }
        }
    }
}
