//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CslaModelTemplates.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CslaModelTemplates.Resources.ValidationText", typeof(ValidationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player code cannot exceed {1} characters..
        /// </summary>
        public static string Player_PlayerCode_MaxLength {
            get {
                return ResourceManager.GetString("Player_PlayerCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player code is not unique..
        /// </summary>
        public static string Player_PlayerCode_NotUnique {
            get {
                return ResourceManager.GetString("Player_PlayerCode_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player code is required..
        /// </summary>
        public static string Player_PlayerCode_Required {
            get {
                return ResourceManager.GetString("Player_PlayerCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player name cannot exceed {1} characters..
        /// </summary>
        public static string Player_PlayerName_MaxLength {
            get {
                return ResourceManager.GetString("Player_PlayerName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player name is required..
        /// </summary>
        public static string Player_PlayerName_Required {
            get {
                return ResourceManager.GetString("Player_PlayerName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new team name is required..
        /// </summary>
        public static string RenameTeam_TeamName_Required {
            get {
                return ResourceManager.GetString("RenameTeam_TeamName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code cannot exceed {1} characters..
        /// </summary>
        public static string SimpleTeam_TeamCode_MaxLength {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code is required..
        /// </summary>
        public static string SimpleTeam_TeamCode_Required {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name cannot exceed {1} characters..
        /// </summary>
        public static string SimpleTeam_TeamName_MaxLength {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name is required..
        /// </summary>
        public static string SimpleTeam_TeamName_Required {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code cannot exceed {1} characters..
        /// </summary>
        public static string SimpleTeamSetItem_TeamCode_MaxLength {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code is required..
        /// </summary>
        public static string SimpleTeamSetItem_TeamCode_Required {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name cannot exceed {1} characters..
        /// </summary>
        public static string SimpleTeamSetItem_TeamName_MaxLength {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name is required..
        /// </summary>
        public static string SimpleTeamSetItem_TeamName_Required {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code cannot exceed {1} characters..
        /// </summary>
        public static string Team_TeamCode_MaxLength {
            get {
                return ResourceManager.GetString("Team_TeamCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code is required..
        /// </summary>
        public static string Team_TeamCode_Required {
            get {
                return ResourceManager.GetString("Team_TeamCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name cannot exceed {1} characters..
        /// </summary>
        public static string Team_TeamName_MaxLength {
            get {
                return ResourceManager.GetString("Team_TeamName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name is required..
        /// </summary>
        public static string Team_TeamName_Required {
            get {
                return ResourceManager.GetString("Team_TeamName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code cannot exceed {1} characters..
        /// </summary>
        public static string TeamSetItem_TeamCode_MaxLength {
            get {
                return ResourceManager.GetString("TeamSetItem_TeamCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code is required..
        /// </summary>
        public static string TeamSetItem_TeamCode_Required {
            get {
                return ResourceManager.GetString("TeamSetItem_TeamCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name cannot exceed {1} characters..
        /// </summary>
        public static string TeamSetItem_TeamName_MaxLength {
            get {
                return ResourceManager.GetString("TeamSetItem_TeamName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name is required..
        /// </summary>
        public static string TeamSetItem_TeamName_Required {
            get {
                return ResourceManager.GetString("TeamSetItem_TeamName_Required", resourceCulture);
            }
        }
    }
}
