using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerUI;
using System.IO;

namespace CslaModelTemplates.WebApi.Extensions
{
    /// <summary>
    /// Provides methods to configure swagger.
    /// </summary>
    public static class SwaggerExtensions
    {
        /// <summary>
        /// Defines documents generated by swagger.
        /// </summary>
        /// <param name="services">The container of the application services.</param>
        /// <param name="environment">The hosting environment.</param>
        public static void AddSwaggerDocuments(
            this IServiceCollection services,
            IWebHostEnvironment environment
            )
        {
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc(
                    "v1",
                    new OpenApiInfo
                    {
                        Title = "CslaModelTemplates.WebApi",
                        Version = "v1"
                    });
                string xmlFile = $"{environment.ApplicationName}.xml";
                string xmlPath = Path.Combine(environment.ContentRootPath, xmlFile);
                c.IncludeXmlComments(xmlPath, true);
            });
        }

        /// <summary>
        /// Adds swagger to the HTTP request pipeline.
        /// </summary>
        /// <param name="app">The application builder.</param>
        /// <param name="environment">The hosting environment.</param>
        public static void UseSwaggerEndpoint(
            this IApplicationBuilder app,
            IHostEnvironment environment
            )
        {
            if (environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint(
                        "/swagger/v1/swagger.json",
                        "CslaModelTemplates.WebApi v1"
                        );
                    c.DocExpansion(DocExpansion.None);
                });
            }
        }
    }
}
